language: objective-c

branches:
  only:
    - master

podfile: ./Demo/Podfile
osx_image: xcode8.2

script:
  - xctool -workspace ./Demo/Demo.xcworkspace -scheme Demo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
